channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.2
  - jupyter
  - pandas=1.2.1
  - scikit-learn=0.23.2
  - numpy=1.19.2
  - matplotlib=3.3.2
  - seaborn=0.11.1
  - python-graphviz=0.15 
  - xlrd=2.0.1
  - xgboost=1.3.0
  - shap=0.37.0